spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/java0515
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
security:
  student:
    name: "Stefan"
    campusName: "九江学院"
